version: '3.8'

networks:
  mavy:
    driver: bridge

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    environment:
      PORT: ${PORT}
    networks:
      - mavy
    restart: always
    depends_on:
      - database
      - redis
  database:
    container_name: database
    image: postgres:15-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_HOST=${DB_HOST}
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mavy
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - mavy
    restart: always
  database-backup:
    container_name: database-backup
    build:
      context: .
      dockerfile: backup.Dockerfile
    tty: true
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PORT=${DB_PORT}
      - PGPASSWORD=${DB_PASS}
    depends_on: [database]
    restart: unless-stopped
    links:
      - database
    networks:
      - mavy
volumes:
  pgdata:
